### ISSUE TITLE
About the calculation of the loss function.

### ISSUE THREAD

**Issue by fpan98** [chenpan0615/FCCDN_pytorch#1]
Label[0] in the loss function refers to the label of change map. What does label[1] refer to?
![image](https://user-images.githubusercontent.com/51882354/135701974-e47ff553-81c9-4b3d-86ef-40af57174744.png)

**Comment by chenpan0615** [comment]
您好 感谢您的关注！label[0]和label[1]都是change mask，只不过我的辅助loss分支的score没有上采样到原图尺寸（下采样了两倍），所以label[1]是下采样了两倍的change mask。希望我的回答对您有帮助，谢谢！
