### ISSUE TITLE
关于训练的batchsize

### ISSUE THREAD

**Issue by walking-shadow** [chenpan0615/FCCDN_pytorch#10]
我用自己的训练框架和这里的模型，同时使用24GB显存的RTX A5000显卡，但是对于256×256的图片，我最高只可以设置到16的batchsize，设置为32就会显示显存不足了，请问可以发布您的训练代码吗？或者请问您使用了哪些能够降低显存的方法呢？

**Comment by chenpan0615** [comment]
256只能到16是有点不合理，你网络完全用的我给的配置吗？或者能够用我提供的pth推理吗？

**Comment by walking-shadow** [comment]
发现是自己代码框架的问题了，感谢作者！
