### ISSUE TITLE
关于验证中计算指标为0，而训练中计算指标不为0

### ISSUE THREAD

**Issue by walking-shadow** [chenpan0615/FCCDN_pytorch#11]
作者你好！
我在训练代码中model.train()之后计算预测结果，结果图是正常的，而如果在model.eval()之后计算预测结果，预测结果会是全黑，导致计算的所有指标都是0。
请问你在训练过程中是否有这样的现象呢？还是因为使用了SynchronizedBatchNorm2d，它的效果对Batchnorm与eval的效果很相似，所以在验证的时候没有加入model.eval()这行代码呢？

**Comment by chenpan0615** [comment]
验证之前肯定是要model.eval()的，不然验证集就参与了bn的计算，验证完记得model.train()。你的验证集损失正常下降吗？我觉得应该是下降的，你这个情况，应该是网络对验证集泛化能力不行，有时候会这样，可以让他多跑跑，后面验证集就会有精度了。
