### ISSUE TITLE
Training time in efficiency test

### ISSUE THREAD

**Issue by walking-shadow** [chenpan0615/FCCDN_pytorch#13]
你好！我对论文中efficiency test中的training time有点疑问，请问training time的测量是让模型在12GB显存下设置最大的batch size，在WHU上训练完成的时间，还是训练固定epoch的时间呢？如果是前者的话，我注意到论文中FCCDN在WHU上的训练曲线，在大概80epoch才收敛，但是训练时间只有150s，也就是说基本2s训练一个epoch，这对于12GB的显存感觉是不太可能的；如果是后者，设定的固定epoch是多少呢？这样对比又是否公平呢？
非常希望能够解答我的疑问，这对于我现在的工作很重要，非常感谢！

**Comment by chenpan0615** [comment]
你好，训练时间是指网络在最大batch size的条件下跑完一个epoch的时间，简单的代表训练速度，这个只是在我的实验环境下横向比较，算是比较公平，如果你想根据我的实验结果也做对比的话，建议还是自己都跑一遍

**Comment by walking-shadow** [comment]
非常感谢你的解答！
