### ISSUE TITLE
SSL&DFM

### ISSUE THREAD

**Issue by lm-ZHAO98** [chenpan0615/FCCDN_pytorch#4]
For the SSL-based feature constraint strategy, we only test it with theDED backbone.
前辈，SSL为什么不能用于FCS框架呢？还有DFM的泛化能力怎么样，能直接用于其他网络或者替换差分特征融合吗？
小白求教，谢谢谢谢！

**Comment by chenpan0615** [comment]
> For the SSL-based feature constraint strategy, we only test it with theDED backbone. 前辈，SSL为什么不能用于FCS框架呢？还有DFM的泛化能力怎么样，能直接用于其他网络或者替换差分特征融合吗？ 小白求教，谢谢谢谢！

1、SSL需要额外的语义分割分支，FCS一般是不具备这种辅助分支的，而DED有两个额外的解码器，所以才能适用。
2、DFM可以用作任何孪生网络的双时相特征融合，当然可能不同任务效果会有差异，我测试大部分任务效果不错（除了有个任务，要求区分建筑物新增和拆除，这个上面效果不太好）。

**Comment by lm-ZHAO98** [comment]
感谢大佬！

**Comment by lm-ZHAO98** [comment]
感谢大佬！
