### ISSUE TITLE
DFM

### ISSUE THREAD

**Issue by lm-ZHAO98** [chenpan0615/FCCDN_pytorch#5]
你好前辈，我想知道（Dense fusion module，DFM）中使用Dense fusion命名模块，这个密集融合指的是DFM模块内部每个分支上的残差连接，还是指您提出的FCCDN中采用多个DFM模块呢？

**Comment by chenpan0615** [comment]
你好，DFM的的密集连接模块指的是内部的残差连接，多个DFM模块就跟普通的cat一样没啥特别的。

**Comment by lm-ZHAO98** [comment]
感谢回复！

**Comment by lm-ZHAO98** [comment]
你好前辈，论文中对DFM有这样的描述“The sum branch is used to enhance the edge information, and the difference branch is used to generate change regions”，差分支我可以理解，想请教一下为什么和分支通过逐点相加可以增强边缘信息呢？

**Comment by chenpan0615** [comment]
你好，首先这个结构因为不是相减，不太可能学习变化信息。当时设计的时候一开始是为了作为残差使用，但是在可视化特征图的时候，发现他能很好的把建筑物边界学习出来，而diff模块主要学习的是变化区域范围，两组特征融合就可以得到精细的变化特征。下面就是特征图效果。
![Screenshot 2022-04-18 151546](https://user-images.githubusercontent.com/49430995/163774827-f167b6ee-bb84-4ab5-84eb-7de5b3422a87.png)

**Comment by lm-ZHAO98** [comment]
感谢您的回复！如果能补一张add和diff融合后的可视化图就更好了。
